tap "homebrew/bundle"
brew "awscli"
brew "dockutil"
brew "fzf"
brew "git-lfs"
brew "golangci-lint"
brew "jq"
brew "mas"
brew "neovim"
brew "nodenv"
brew "ripgrep"
brew "tfenv"
brew "tmux"
brew "tree"
brew "zoxide"
cask "docker"
cask "discord"
cask "figma"
cask "font-hack-nerd-font"
cask "font-jetbrains-mono"
cask "freecad"
cask "insomnia"
cask "iterm2"
cask "notion"
cask "obs"
cask "rectangle"
cask "slack"
cask "sourcetree"
cask "todoist"
cask "visual-studio-code"
mas "Bitwarden", id: 1352778147
mas "Compressor", id: 424390742
mas "Eno From Capital One", id: 1590422864
mas "Final Cut Pro", id: 424389933
mas "Logic Pro", id: 634148309
mas "Xcode", id: 497799835
vscode "connor4312.esbuild-problem-matchers"
vscode "dbaeumer.vscode-eslint"
vscode "github.codespaces"
vscode "github.vscode-github-actions"
vscode "golang.go"
vscode "hashicorp.terraform"
vscode "ms-azuretools.vscode-docker"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode.extension-test-runner"
